version: v1.0.0.{build}
image:
  - Visual Studio 2019

platform:
  - x64

install:
  # prepare tools
  # - ps: Push-Location C:/
  - ps: Get-Location
  # python
  - ps: Invoke-WebRequest "https://www.python.org/ftp/python/3.9.5/python-3.9.5-amd64.exe" -UseBasicParsing -OutFile ./python.exe
  - ps: ./python.exe /quiet InstallAllUsers=0 Include_doc=0 PrependPath=1 TargetDir="./python-install"

build_script:
  - ps: Compress-Archive -Path ./python-install -DestinationPath ./python-3.9.5.zip

after_build:
  # publish zip archive
  - ps: Push-AppveyorArtifact ./python-3.9.5.zip -FileName python-3.9.5.zip -DeploymentName "python-zip"
  - ps: (Get-FileHash ./python-3.9.5.zip -Algorithm SHA256).Hash.ToLower() | Out-File ./shafile -Encoding ASCII -NoNewLine

  # publish sha file
  - ps: Push-AppveyorArtifact ./shafile -FileName python-3.9.5.sha256 -DeploymentName "python-shafile"
