name: windows

on: push

jobs:
  python:
    strategy:
      matrix:
        arch: ["32", "64"]
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: false
      - name: prepare llvm
        run: |
          python get_llvm_ps1.py 14.0.0 ${{ matrix.arch }}
          ./get_llvm_14.0.0_${{ matrix.arch }}.ps1
      - name: publish to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: xq114/appveyor-hello
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: clang+llvm-14.0.0-win${{ matrix.arch }}.zip
          asset_name: clang+llvm-14.0.0-win${{ matrix.arch }}.zip
          tag: "14.0.0"
          body: "llvm for windows 14.0.0"
