name: windows

on: push

jobs:
  python:
    strategy:
      matrix:
        arch: ["32", "64"]
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: false
      - name: prepare python
        run: |
          python get_python_ps1.py 3.7.9 ${{ matrix.arch }}
          ./get_python_3.7.9_${{ matrix.arch }}.ps1
      - name: publish to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: xq114/appveyor-hello
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: python-3.7.9.win${{ matrix.arch }}.zip
          asset_name: python-3.7.9.win${{ matrix.arch }}.zip
          tag: "3.7.9"
          body: "python for windows 3.7.9"
